//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "../Apollo/MTLModel.h"

#import "../Apollo/MTLJSONSerializing-Protocol.h"

@class NSString;

@interface RKThing : MTLModel <MTLJSONSerializing>
{
    NSString *_kind;
    NSString *_identifier;
    NSString *_fullName;
}

+ (id)JSONKeyPathsByPropertyKey;

@property(copy, nonatomic) NSString *fullName; // @synthesize fullName=_fullName;
@property(readonly, copy, nonatomic) NSString *identifier; // @synthesize identifier=_identifier;
@property(readonly, copy, nonatomic) NSString *kind; // @synthesize kind=_kind;
- (_Bool)isEqual:(id)arg1;

@end

