//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "RKCreated.h"

@interface RKVotable : RKCreated
{
    unsigned long long _upvotes;
    unsigned long long _downvotes;
    unsigned long long _voteStatus;
    long long _score;
}

+ (id)voteStatusJSONTransformer;
+ (id)JSONKeyPathsByPropertyKey;
@property(nonatomic) long long score; // @synthesize score=_score;
@property(readonly, nonatomic) unsigned long long voteStatus; // @synthesize voteStatus=_voteStatus;
@property(readonly, nonatomic) unsigned long long downvotes; // @synthesize downvotes=_downvotes;
@property(readonly, nonatomic) unsigned long long upvotes; // @synthesize upvotes=_upvotes;
- (_Bool)voted;
- (_Bool)downvoted;
- (_Bool)upvoted;
- (void)nrt_performVoteAction:(long long)arg1;
- (void)nrt_updateVoteStatus:(unsigned long long)arg1 upvotes:(long long)arg2 downvotes:(long long)arg3;
- (void)nrt_updateVoteStatus:(unsigned long long)arg1 voteDirection:(long long)arg2;

@end

