//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "RDKThing.h"

@class NSDate;

@interface RDKCreated : RDKThing
{
    NSDate *_createdUTC;
}

+ (id)createdUTCJSONTransformer;
+ (id)JSONKeyPathsByPropertyKey;
+ (unsigned long long)modelVersion;
+ (_Bool)supportsSecureCoding;
@property(retain, nonatomic) NSDate *createdUTC; // @synthesize createdUTC=_createdUTC;

@end

