//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "MTLModel.h"

#import "MTLJSONSerializing-Protocol.h"

@class NSString;

@interface RDKThing : MTLModel <MTLJSONSerializing, NSSecureCoding>
{
    NSString *_kindName;
    NSString *_identifier;
    NSString *_fullName;
}

+ (id)JSONKeyPathsByPropertyKey;
+ (unsigned long long)modelVersion;
+ (_Bool)supportsSecureCoding;
@property(copy, nonatomic) NSString *fullName; // @synthesize fullName=_fullName;
@property(copy, nonatomic) NSString *identifier; // @synthesize identifier=_identifier;
@property(copy, nonatomic) NSString *kindName; // @synthesize kindName=_kindName;
- (unsigned long long)hash;
- (_Bool)isEqual:(id)arg1;
- (_Bool)isEqualToDiffableObject:(id)arg1;
- (id)diffIdentifier;

@end

