//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "RDKCreated.h"

@interface RDKVotable : RDKCreated
{
    long long _upvotes;
    long long _downvotes;
    long long _score;
    unsigned long long _voteStatus;
}

+ (id)voteStatusJSONTransformer;
+ (id)JSONKeyPathsByPropertyKey;
+ (unsigned long long)modelVersion;
+ (_Bool)supportsSecureCoding;
@property(nonatomic) unsigned long long voteStatus; // @synthesize voteStatus=_voteStatus;
@property(nonatomic) long long score; // @synthesize score=_score;
@property(nonatomic) long long downvotes; // @synthesize downvotes=_downvotes;
@property(nonatomic) long long upvotes; // @synthesize upvotes=_upvotes;
- (_Bool)voted;
- (_Bool)downvoted;
- (_Bool)upvoted;

@end

