//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "JMOutlineNode.h"

@class NSArray, NSAttributedString, NSString;

@interface BaseStyledTextNode : JMOutlineNode
{
    unsigned long long _numThumbnailsPrefetched;
}

@property unsigned long long numThumbnailsPrefetched; // @synthesize numThumbnailsPrefetched=_numThumbnailsPrefetched;
- (void)prefetchThumbnailsToCacheOnComplete:(id)arg1;
- (double)heightForBodyConstrainedToWidth:(double)arg1;
@property(readonly) NSArray *thumbLinks;
@property(readonly) NSAttributedString *styledText;
- (_Bool)containsRestrictedContent;
- (_Bool)containsNSFWContent;
@property(readonly) NSString *elementId;

@end

