//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "BaseStyledTextNode.h"

@class Comment, Post;

@interface CommentNode : BaseStyledTextNode
{
    _Bool _firstComment;
    _Bool _isContext;
    Comment *_comment;
    Post *_post;
}

+ (Class)cellClass;
+ (id)nodeForComment:(id)arg1 level:(unsigned long long)arg2;
@property _Bool isContext; // @synthesize isContext=_isContext;
@property _Bool firstComment; // @synthesize firstComment=_firstComment;
@property(retain) Post *post; // @synthesize post=_post;
@property(retain) Comment *comment; // @synthesize comment=_comment;
- (void)prefetchThumbnails;
- (id)thumbLinks;
- (double)heightForBodyConstrainedToWidth:(double)arg1;
- (id)styledText;
- (id)elementId;
- (_Bool)containsRestrictedContent;
- (_Bool)containsNSFWContent;
- (id)initWithComment:(id)arg1 level:(unsigned long long)arg2;

@end

