//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "BaseStyledTextNode.h"

@class Comment, NSNumber, Post;

@interface CommentPostHeaderNode : BaseStyledTextNode
{
    _Bool _isPlaceholderPost;
    _Bool _forceImageLoad;
    Post *_post;
    Comment *_comment;
    NSNumber *_inlineImageAspectRatio;
}

+ (Class)cellClass;
+ (id)placeholderNodeForPost:(id)arg1;
+ (id)nodeForHeaderPost:(id)arg1;
@property _Bool forceImageLoad; // @synthesize forceImageLoad=_forceImageLoad;
@property _Bool isPlaceholderPost; // @synthesize isPlaceholderPost=_isPlaceholderPost;
@property(retain) NSNumber *inlineImageAspectRatio; // @synthesize inlineImageAspectRatio=_inlineImageAspectRatio;
@property(retain) Comment *comment; // @synthesize comment=_comment;
@property(retain) Post *post; // @synthesize post=_post;
- (id)thumbLinks;
- (double)heightForBodyConstrainedToWidth:(double)arg1;
- (id)styledText;
- (id)elementId;
- (_Bool)containsRestrictedContent;
- (_Bool)containsNSFWContent;

@end

