//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMutableArray;
@protocol JMOutlineNodeProtocol;

@interface JMOutlineNode : NSObject
{
    _Bool _editable;
    int state_;
    NSObject<JMOutlineNodeProtocol> *delegate_;
    id onSelect_;
    unsigned long long level_;
    JMOutlineNode *parentNode_;
    NSMutableArray *childNodes_;
}

+ (Class)cellClass;
+ (id)node;
@property _Bool editable; // @synthesize editable=_editable;
@property(retain, nonatomic) NSMutableArray *childNodes; // @synthesize childNodes=childNodes_;
@property __weak JMOutlineNode *parentNode; // @synthesize parentNode=parentNode_;
@property int state; // @synthesize state=state_;
@property unsigned long long level; // @synthesize level=level_;
@property(copy) id onSelect; // @synthesize onSelect=onSelect_;
@property __weak NSObject<JMOutlineNodeProtocol> *delegate; // @synthesize delegate=delegate_;
- (void)refresh;
- (void)hideNode;
- (void)expandNode;
- (void)hideChildren;
- (void)collapseNode;
- (id)allChildren;
- (void)addChildNode:(id)arg1;
- (_Bool)hidden;
- (_Bool)collapsed;
@property(readonly) _Bool selected;
- (id)init;
- (void)dealloc;

@end

