//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "VotableElement.h"

@class NSAttributedString, NSDictionary, NSString;

@interface Post : VotableElement <NSCoding>
{
    _Bool visited_;
    _Bool _stickied;
    _Bool _nsfw;
    _Bool _saved;
    _Bool _hidden;
    _Bool _selfPost;
    _Bool _reported;
    _Bool _promoted;
    long long score_;
    NSString *_title;
    NSString *_selftext;
    NSString *_selftextHtml;
    NSString *_linkFlairText;
    NSString *_url;
    NSString *_domain;
    NSString *_rawThumbnail;
    NSDictionary *_preview;
    NSDictionary *_subredditDetail;
    unsigned long long _gilded;
    long long _numComments;
    unsigned long long _numberOfImagesInCommentThread;
    NSAttributedString *_cachedStyledTitle;
    NSString *_contextCommentIdent;
}

+ (id)postSkeletonFromRedditUrl:(id)arg1;
+ (id)postFromDictionary:(id)arg1;
@property(retain) NSString *contextCommentIdent; // @synthesize contextCommentIdent=_contextCommentIdent;
@property(retain, nonatomic) NSAttributedString *cachedStyledTitle; // @synthesize cachedStyledTitle=_cachedStyledTitle;
@property unsigned long long numberOfImagesInCommentThread; // @synthesize numberOfImagesInCommentThread=_numberOfImagesInCommentThread;
@property long long numComments; // @synthesize numComments=_numComments;
@property unsigned long long gilded; // @synthesize gilded=_gilded;
@property _Bool promoted; // @synthesize promoted=_promoted;
@property _Bool reported; // @synthesize reported=_reported;
@property _Bool selfPost; // @synthesize selfPost=_selfPost;
@property _Bool hidden; // @synthesize hidden=_hidden;
@property _Bool saved; // @synthesize saved=_saved;
@property _Bool nsfw; // @synthesize nsfw=_nsfw;
@property _Bool stickied; // @synthesize stickied=_stickied;
@property(retain, nonatomic) NSDictionary *subredditDetail; // @synthesize subredditDetail=_subredditDetail;
@property(retain, nonatomic) NSDictionary *preview; // @synthesize preview=_preview;
@property(retain, nonatomic) NSString *rawThumbnail; // @synthesize rawThumbnail=_rawThumbnail;
@property(retain, nonatomic) NSString *domain; // @synthesize domain=_domain;
@property(retain, nonatomic) NSString *url; // @synthesize url=_url;
@property(retain, nonatomic) NSString *linkFlairText; // @synthesize linkFlairText=_linkFlairText;
@property(retain, nonatomic) NSString *selftextHtml; // @synthesize selftextHtml=_selftextHtml;
@property(retain, nonatomic) NSString *selftext; // @synthesize selftext=_selftext;
@property(retain, nonatomic) NSString *title; // @synthesize title=_title;
@property(nonatomic) _Bool visited; // @synthesize visited=visited_;
- (void)setScore:(long long)arg1;
- (long long)score;
@property(readonly) NSString *linkFlairTextForPresentation;
@property(readonly) _Bool hasExternalLink;
@property(readonly) NSString *linkTypeIconName;
@property(readonly) _Bool needsNSFWWarning;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
@property(readonly) int linkType;
- (_Bool)isInVisitedList;
- (void)markVisited;
@property(readonly) NSString *tinyDomain;
@property(readonly) NSString *thumbnail;
- (void)updateVisitedStatus;
- (void)flushCachedStyles;

@end

