//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSDate, NSDictionary, NSString;

@interface VotableElement : NSObject
{
    _Bool _deleted;
    _Bool _isScoreHidden;
    _Bool _isModdable;
    _Bool _isSpam;
    int _voteState;
    NSString *_ident;
    NSString *_name;
    NSString *_author;
    NSString *_timeAgo;
    NSString *_subreddit;
    NSString *_subredditId;
    NSString *_permalink;
    NSString *_distinguishedStr;
    NSDate *_createdDate;
    long long _score;
    NSString *_approvedBy;
    NSString *_bannedBy;
    long long _numReports;
    NSDictionary *_rawDictionary;
    NSString *_elementCategoryNameForAnalytics;
}

@property(readonly) NSString *elementCategoryNameForAnalytics; // @synthesize elementCategoryNameForAnalytics=_elementCategoryNameForAnalytics;
@property(retain, nonatomic) NSDictionary *rawDictionary; // @synthesize rawDictionary=_rawDictionary;
@property(nonatomic) _Bool isSpam; // @synthesize isSpam=_isSpam;
@property(nonatomic) _Bool isModdable; // @synthesize isModdable=_isModdable;
@property(nonatomic) long long numReports; // @synthesize numReports=_numReports;
@property(retain, nonatomic) NSString *bannedBy; // @synthesize bannedBy=_bannedBy;
@property(retain, nonatomic) NSString *approvedBy; // @synthesize approvedBy=_approvedBy;
@property(nonatomic) long long score; // @synthesize score=_score;
@property(retain) NSDate *createdDate; // @synthesize createdDate=_createdDate;
@property(retain, nonatomic) NSString *distinguishedStr; // @synthesize distinguishedStr=_distinguishedStr;
@property(retain, nonatomic) NSString *permalink; // @synthesize permalink=_permalink;
@property(retain, nonatomic) NSString *subredditId; // @synthesize subredditId=_subredditId;
@property(retain, nonatomic) NSString *subreddit; // @synthesize subreddit=_subreddit;
@property(retain, nonatomic) NSString *timeAgo; // @synthesize timeAgo=_timeAgo;
@property(retain, nonatomic) NSString *author; // @synthesize author=_author;
@property(retain, nonatomic) NSString *name; // @synthesize name=_name;
@property(retain, nonatomic) NSString *ident; // @synthesize ident=_ident;
@property _Bool isScoreHidden; // @synthesize isScoreHidden=_isScoreHidden;
@property _Bool deleted; // @synthesize deleted=_deleted;
@property int voteState; // @synthesize voteState=_voteState;
- (void)reportAnalyticEventWithAction:(id)arg1;
- (void)modMarkAsSpam;
- (void)modRemove;
- (void)modApprove;
- (void)i_modUpdateRawDictionaryWithIVars;
- (void)replaceRawDictionaryKey:(id)arg1 withObjectOrNil:(id)arg2;
@property(readonly) int moderationState;
- (void)downvote;
- (void)upvote;
@property(readonly) NSString *formattedScoreWithText;
@property(readonly) NSString *formattedScoreTinyWithPlus;
@property(readonly) NSString *formattedScore;
@property(readonly) NSString *formattedScoreTiny;
- (id)legacyVoteDictionary;
@property(readonly) _Bool isFromAdmin;
@property(readonly) _Bool isFromModerator;
@property(readonly) _Bool isMine;
- (int)ownershipToUser:(id)arg1;
- (id)legacyDictionary;
@property(readonly) NSString *tinyTimeAgo;
- (void)setVotableElementPropertiesFromDictionary:(id)arg1;

@end

